run_name: ../ada_narval/CO2-catalysis/bicarb_tests
dataset: bicarb
num_runs: 2
models: ["Ph", "GP+Ph", "MLP", "GP"]
system_phase: gas
property_name: 'FE_CO'
EI_reference: "max"
num_iter: 101
normalize_inputs: True
normalize_outputs: False
torch_seed: 0
use_existing_results: True
