default_config = {
    "run_name": "out",
    "num_iter": 101,
    "make_plots": False,
    "normalize_inputs": True,
    "normalize_outputs": False,
    "EI_reference": "max",
    "UCB_beta": 1.0,
    "system_phase": None,
    "dataset": "gas",
    "property_name": "FE (Eth)",
    "data_file": None,
    "acquisition": "EI",
    "extra_sink": False,
    "constant_J_in": False,
    "current_density": None,
    "zero_eps_thickness": None,
}
